/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kgu_kscp_erasure_Encoder */

#ifndef _Included_kgu_kscp_erasure_Encoder
#define _Included_kgu_kscp_erasure_Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kgu_kscp_erasure_Encoder
 * Method:    jerasureEncoding
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kgu_kscp_erasure_Encoder_jerasureEncoding
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
