/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kgu_islab_erasure_Decoder */

#ifndef _Included_kgu_islab_erasure_Decoder
#define _Included_kgu_islab_erasure_Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kgu_islab_erasure_Decoder
 * Method:    jerasureDecoding
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kgu_islab_erasure_Decoder_jerasureDecoding
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
